server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangtianruipopo/com.wtr.git
          username: wangtianruipopo
          password: 964500wang
